use axum::{
    Json,
    extract::{Path, State},
    http::StatusCode,
    response::{IntoResponse, Response},
};
use chrono::Utc;
use plinth_shared::{
    AddTagRequest, BlogPost, ContentFormat, CreateTodoRequest, PublishArticleRequest, SiteContent,
    Tag, TodoItem, UpdateSiteContentRequest, UpdateTodoRequest,
};
use serde::Serialize;

use crate::{
    AppState,
    actors::content_cache::{GetAllTags, GetSiteContent, InvalidateCache},
    db_helpers::take_as,
    services::{
        db::{sync_post_tags_cache, sync_todo_tags_cache},
        markdown_processor::{generate_slug, parse_markdown},
    },
};

/// Response for successful article publication
#[derive(Debug, Serialize)]
pub struct PublishArticleResponse {
    pub success: bool,
    pub slug: String,
    pub id: Option<String>,
    pub message: String,
}

/// Error response for article publication failures
#[derive(Debug, Serialize)]
pub struct ErrorResponse {
    pub error: String,
    pub details: Option<String>,
}

impl IntoResponse for ErrorResponse {
    fn into_response(self) -> Response {
        (StatusCode::BAD_REQUEST, Json(self)).into_response()
    }
}

/// Publish a new blog article
///
/// This endpoint accepts markdown content with optional frontmatter,
/// processes it into HTML, generates an embedding, and stores it in SurrealDB.
pub async fn publish_article(
    State(state): State<AppState>,
    Json(request): Json<PublishArticleRequest>,
) -> Result<Json<PublishArticleResponse>, ErrorResponse> {
    let content_format = request
        .content_format
        .clone()
        .unwrap_or(ContentFormat::Markdown);

    // Process content based on format
    let (html_content, markdown_content, frontmatter, reading_time) = match &content_format {
        ContentFormat::Markdown => {
            let parsed = parse_markdown(&request.content).map_err(|e| ErrorResponse {
                error: "Failed to parse markdown".to_string(),
                details: Some(e),
            })?;
            (
                parsed.html_content,
                parsed.markdown_content,
                parsed.frontmatter,
                parsed.reading_time_minutes,
            )
        }
        ContentFormat::Typst => {
            // For Typst, the CLI pre-renders HTML
            let html = request.html_content.clone().ok_or_else(|| ErrorResponse {
                error: "Typst posts require pre-rendered HTML".to_string(),
                details: Some(
                    "Set html_content in the request (CLI compiles Typst to HTML)".to_string(),
                ),
            })?;
            let reading_time = BlogPost::calculate_reading_time(&request.content);
            (html, request.content.clone(), None, reading_time)
        }
    };

    // Determine title (from frontmatter or request)
    let title = request
        .title
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.title.clone()))
        .ok_or_else(|| ErrorResponse {
            error: "Title is required".to_string(),
            details: Some("Provide title in request or frontmatter".to_string()),
        })?;

    // Generate slug (from request, frontmatter, or title)
    let slug = request.slug.unwrap_or_else(|| generate_slug(&title));

    let tags = request
        .tags
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.tags.clone()))
        .unwrap_or_default();

    let default_author = state.config.site.author.name.clone();
    let author = request
        .author
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.author.clone()))
        .unwrap_or(default_author);

    let description = request
        .description
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.description.clone()))
        .unwrap_or_default();

    let published = request
        .published
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.published))
        .unwrap_or(true);

    let featured = request
        .featured
        .or_else(|| frontmatter.as_ref().and_then(|fm| fm.featured))
        .unwrap_or(false);

    // Generate vector embedding if provided in request
    // (CLI tool will generate embeddings locally and send them)
    let embedding = request.embedding;

    // Create BlogPost record
    let blog_post = BlogPost {
        id: None, // Will be generated by SurrealDB
        slug: slug.clone(),
        title: title.clone(),
        description,
        content: markdown_content,
        html_content,
        published_at: Utc::now(),
        updated_at: None,
        author,
        tags: tags.clone(),
        featured,
        published,
        reading_time_minutes: reading_time,
        embedding,
        content_format,
    };

    // Insert into SurrealDB (convert through serde_json::Value for SurrealValue compat)
    let db = &state.db;
    let blog_post_value = serde_json::to_value(&blog_post).map_err(|e| ErrorResponse {
        error: "Failed to serialize blog post".to_string(),
        details: Some(e.to_string()),
    })?;
    let created_value: Option<serde_json::Value> =
        db.create("blog_posts")
            .content(blog_post_value)
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to create blog post in database".to_string(),
                details: Some(e.to_string()),
            })?;

    let created_post: BlogPost = created_value
        .ok_or_else(|| ErrorResponse {
            error: "No blog post returned from database".to_string(),
            details: None,
        })
        .and_then(|v| {
            serde_json::from_value(v).map_err(|e| ErrorResponse {
                error: "Failed to deserialize created blog post".to_string(),
                details: Some(e.to_string()),
            })
        })?;

    // Create graph relations for tags
    for tag_name in &tags {
        let tag_slug = generate_slug(tag_name);
        db.query(
            r#"
            IF (SELECT count() FROM tags WHERE slug = $tag_slug) = 0 THEN
                CREATE tags CONTENT {
                    name: $tag_name,
                    slug: $tag_slug,
                    created_at: time::now()
                }
            END;

            LET $post = (SELECT VALUE id FROM blog_posts WHERE slug = $post_slug LIMIT 1)[0];
            LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
            RELATE $post->tagged->$tag CONTENT { created_at: time::now() };
        "#,
        )
        .bind(("tag_name", tag_name.to_string()))
        .bind(("tag_slug", tag_slug))
        .bind(("post_slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to create tag relation".to_string(),
            details: Some(e.to_string()),
        })?;
    }

    // Invalidate content cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(PublishArticleResponse {
        success: true,
        slug: slug.clone(),
        id: created_post.id,
        message: format!("Article '{}' published successfully", title),
    }))
}

/// Delete a blog article by slug (admin only)
#[allow(dead_code)]
pub async fn delete_article(
    State(state): State<AppState>,
    slug: String,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    // Delete from SurrealDB
    let db = &state.db;

    // First find the article
    let query = "SELECT * FROM blog_posts WHERE slug = $slug LIMIT 1";
    let mut result = db
        .query(query)
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Database query failed".to_string(),
            details: Some(e.to_string()),
        })?;

    let posts: Vec<BlogPost> = take_as(&mut result, 0).map_err(|e| ErrorResponse {
        error: "Failed to parse query result".to_string(),
        details: Some(e),
    })?;

    if posts.is_empty() {
        return Err(ErrorResponse {
            error: "Article not found".to_string(),
            details: Some(format!("No article with slug '{}'", slug)),
        });
    }

    // Delete the article
    let post_id = posts[0].id.as_ref().ok_or_else(|| ErrorResponse {
        error: "Article has no ID".to_string(),
        details: None,
    })?;

    let _: Option<serde_json::Value> =
        db.delete(("blog_posts", post_id.as_str()))
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to delete article".to_string(),
                details: Some(e.to_string()),
            })?;

    // Invalidate cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Article '{}' deleted successfully", slug)
    })))
}

/// List all tags with post counts
pub async fn list_tags(State(state): State<AppState>) -> Result<Json<Vec<Tag>>, ErrorResponse> {
    let tags = state
        .content_cache
        .ask(GetAllTags)
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to query tags".to_string(),
            details: Some(e.to_string()),
        })?;

    Ok(Json(tags))
}

/// Add a tag to a post
pub async fn add_tag_to_post(
    State(state): State<AppState>,
    Path(post_slug): Path<String>,
    Json(request): Json<AddTagRequest>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;
    let tag_slug = generate_slug(&request.tag);

    // Ensure tag exists
    db.query(
        r#"
        IF (SELECT count() FROM tags WHERE slug = $tag_slug) = 0 THEN
            CREATE tags CONTENT {
                name: $tag_name,
                slug: $tag_slug,
                created_at: time::now()
            }
        END;
    "#,
    )
    .bind(("tag_name", request.tag.clone()))
    .bind(("tag_slug", tag_slug.clone()))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to ensure tag exists".to_string(),
        details: Some(e.to_string()),
    })?;

    // Create relation
    db.query(
        r#"
        LET $post = (SELECT VALUE id FROM blog_posts WHERE slug = $post_slug LIMIT 1)[0];
        LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
        RELATE $post->tagged->$tag CONTENT { created_at: time::now() };
    "#,
    )
    .bind(("post_slug", post_slug.clone()))
    .bind(("tag_slug", tag_slug))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to add tag to post".to_string(),
        details: Some(e.to_string()),
    })?;

    // Sync denormalized cache
    sync_post_tags_cache(db, &post_slug)
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to sync tag cache".to_string(),
            details: Some(e.to_string()),
        })?;

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Tag '{}' added to post '{}'", request.tag, post_slug)
    })))
}

/// Remove a tag from a post
pub async fn remove_tag_from_post(
    State(state): State<AppState>,
    Path((post_slug, tag_slug)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;

    // Delete the relation
    db.query(
        r#"
        LET $post = (SELECT VALUE id FROM blog_posts WHERE slug = $post_slug LIMIT 1)[0];
        LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
        DELETE tagged WHERE in = $post AND out = $tag;
    "#,
    )
    .bind(("post_slug", post_slug.clone()))
    .bind(("tag_slug", tag_slug.clone()))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to remove tag from post".to_string(),
        details: Some(e.to_string()),
    })?;

    // Sync denormalized cache
    sync_post_tags_cache(db, &post_slug)
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to sync tag cache".to_string(),
            details: Some(e.to_string()),
        })?;

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Tag '{}' removed from post '{}'", tag_slug, post_slug)
    })))
}

/// Update site content by key (upsert)
pub async fn update_site_content(
    State(state): State<AppState>,
    Path(key): Path<String>,
    Json(request): Json<UpdateSiteContentRequest>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;

    // Upsert: delete existing then create, using raw SQL for datetime
    db.query(
        r##"
        DELETE FROM site_content WHERE key = $key;
        CREATE site_content CONTENT {
            key: $key,
            title: $title,
            content: $content,
            html_content: $html_content,
            updated_at: time::now()
        };
        "##,
    )
    .bind(("key", key.clone()))
    .bind(("title", request.title))
    .bind(("content", request.content))
    .bind(("html_content", request.html_content))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to update site content".to_string(),
        details: Some(e.to_string()),
    })?;

    // Invalidate cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "key": key,
        "message": format!("Site content '{}' updated successfully", key)
    })))
}

/// Get site content by key
pub async fn get_admin_site_content(
    State(state): State<AppState>,
    Path(key): Path<String>,
) -> Result<Json<Option<SiteContent>>, ErrorResponse> {
    let content = state
        .content_cache
        .ask(GetSiteContent(key))
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to query site content".to_string(),
            details: Some(e.to_string()),
        })?;

    Ok(Json(content))
}

// --- TODO / Bucket List endpoints ---

/// Create a new TODO item
pub async fn create_todo(
    State(state): State<AppState>,
    Json(request): Json<CreateTodoRequest>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;
    let slug = request
        .slug
        .unwrap_or_else(|| generate_slug(&request.title));

    // Use raw SQL for datetime fields (SurrealDB SCHEMAFULL constraint)
    let completed_at_expr = if request.completed {
        "time::now()"
    } else {
        "NONE"
    };

    db.query(format!(
        r#"CREATE todos CONTENT {{
            slug: $slug,
            title: $title,
            description: $description,
            content: $content,
            html_content: $html_content,
            tags: $tags,
            completed: $completed,
            completed_at: {completed_at_expr},
            created_at: time::now(),
            order: $order
        }}"#
    ))
    .bind(("slug", slug.clone()))
    .bind(("title", request.title.clone()))
    .bind(("description", request.description))
    .bind(("content", request.content))
    .bind(("html_content", request.html_content))
    .bind(("tags", request.tags.clone()))
    .bind(("completed", request.completed))
    .bind(("order", request.order))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to create TODO item".to_string(),
        details: Some(e.to_string()),
    })?;

    // Create tag graph relations
    for tag_name in &request.tags {
        let tag_slug = generate_slug(tag_name);
        db.query(
            r#"
            IF (SELECT count() FROM tags WHERE slug = $tag_slug) = 0 THEN
                CREATE tags CONTENT {
                    name: $tag_name,
                    slug: $tag_slug,
                    created_at: time::now()
                }
            END;

            LET $todo = (SELECT VALUE id FROM todos WHERE slug = $todo_slug LIMIT 1)[0];
            LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
            RELATE $todo->todo_tagged->$tag CONTENT { created_at: time::now() };
        "#,
        )
        .bind(("tag_name", tag_name.to_string()))
        .bind(("tag_slug", tag_slug))
        .bind(("todo_slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to create tag relation".to_string(),
            details: Some(e.to_string()),
        })?;
    }

    // Invalidate content cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "slug": slug,
        "message": format!("TODO '{}' created successfully", request.title)
    })))
}

/// Update an existing TODO item (partial update)
pub async fn update_todo(
    State(state): State<AppState>,
    Path(slug): Path<String>,
    Json(request): Json<UpdateTodoRequest>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;

    // Fetch existing item
    let mut result = db
        .query("SELECT * FROM todos WHERE slug = $slug LIMIT 1")
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Database query failed".to_string(),
            details: Some(e.to_string()),
        })?;

    let existing: Vec<TodoItem> = take_as(&mut result, 0).map_err(|e| ErrorResponse {
        error: "Failed to parse query result".to_string(),
        details: Some(e),
    })?;

    if existing.is_empty() {
        return Err(ErrorResponse {
            error: "TODO item not found".to_string(),
            details: Some(format!("No TODO with slug '{}'", slug)),
        });
    }

    let existing = &existing[0];

    // Build SET clauses for non-None fields
    let mut set_parts: Vec<String> = Vec::new();

    if let Some(ref title) = request.title {
        set_parts.push(format!("title = '{}'", title.replace('\'', "\\'")));
    }
    if let Some(ref description) = request.description {
        set_parts.push(format!(
            "description = '{}'",
            description.replace('\'', "\\'")
        ));
    }
    if let Some(ref content) = request.content {
        set_parts.push(format!("content = '{}'", content.replace('\'', "\\'")));
    }
    if let Some(ref html_content) = request.html_content {
        set_parts.push(format!(
            "html_content = '{}'",
            html_content.replace('\'', "\\'")
        ));
    }
    if let Some(ref order) = request.order {
        set_parts.push(format!("order = {}", order));
    }

    // Handle completion status change
    if let Some(completed) = request.completed {
        set_parts.push(format!("completed = {}", completed));
        if completed && !existing.completed {
            // Transitioning to completed — set completed_at
            set_parts.push("completed_at = time::now()".to_string());
        } else if !completed {
            // Transitioning to not completed — clear completed_at
            set_parts.push("completed_at = NONE".to_string());
        }
    }

    if !set_parts.is_empty() {
        let set_clause = set_parts.join(", ");
        db.query(format!(
            "UPDATE todos SET {} WHERE slug = $slug",
            set_clause
        ))
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to update TODO item".to_string(),
            details: Some(e.to_string()),
        })?;
    }

    // Handle tag updates
    if let Some(ref new_tags) = request.tags {
        // Delete existing relations
        db.query(
            r#"
            LET $todo = (SELECT VALUE id FROM todos WHERE slug = $slug LIMIT 1)[0];
            DELETE todo_tagged WHERE in = $todo;
        "#,
        )
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to clear tag relations".to_string(),
            details: Some(e.to_string()),
        })?;

        // Create new relations
        for tag_name in new_tags {
            let tag_slug = generate_slug(tag_name);
            db.query(
                r#"
                IF (SELECT count() FROM tags WHERE slug = $tag_slug) = 0 THEN
                    CREATE tags CONTENT {
                        name: $tag_name,
                        slug: $tag_slug,
                        created_at: time::now()
                    }
                END;

                LET $todo = (SELECT VALUE id FROM todos WHERE slug = $todo_slug LIMIT 1)[0];
                LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
                RELATE $todo->todo_tagged->$tag CONTENT { created_at: time::now() };
            "#,
            )
            .bind(("tag_name", tag_name.to_string()))
            .bind(("tag_slug", tag_slug))
            .bind(("todo_slug", slug.clone()))
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to create tag relation".to_string(),
                details: Some(e.to_string()),
            })?;
        }

        // Sync denormalized tags array
        sync_todo_tags_cache(db, &slug)
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to sync tag cache".to_string(),
                details: Some(e.to_string()),
            })?;
    }

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "slug": slug,
        "message": format!("TODO '{}' updated successfully", slug)
    })))
}

/// Delete a TODO item by slug
pub async fn delete_todo(
    State(state): State<AppState>,
    Path(slug): Path<String>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;

    // Find the item
    let mut result = db
        .query("SELECT * FROM todos WHERE slug = $slug LIMIT 1")
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Database query failed".to_string(),
            details: Some(e.to_string()),
        })?;

    let items: Vec<TodoItem> = take_as(&mut result, 0).map_err(|e| ErrorResponse {
        error: "Failed to parse query result".to_string(),
        details: Some(e),
    })?;

    if items.is_empty() {
        return Err(ErrorResponse {
            error: "TODO item not found".to_string(),
            details: Some(format!("No TODO with slug '{}'", slug)),
        });
    }

    // Delete tag relations and the item itself
    db.query(
        r#"
        LET $todo = (SELECT VALUE id FROM todos WHERE slug = $slug LIMIT 1)[0];
        DELETE todo_tagged WHERE in = $todo;
        DELETE FROM todos WHERE slug = $slug;
    "#,
    )
    .bind(("slug", slug.clone()))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to delete TODO item".to_string(),
        details: Some(e.to_string()),
    })?;

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("TODO '{}' deleted successfully", slug)
    })))
}

/// Add a tag to a TODO item
pub async fn add_tag_to_todo(
    State(state): State<AppState>,
    Path(todo_slug): Path<String>,
    Json(request): Json<AddTagRequest>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;
    let tag_slug = generate_slug(&request.tag);

    // Ensure tag exists
    db.query(
        r#"
        IF (SELECT count() FROM tags WHERE slug = $tag_slug) = 0 THEN
            CREATE tags CONTENT {
                name: $tag_name,
                slug: $tag_slug,
                created_at: time::now()
            }
        END;
    "#,
    )
    .bind(("tag_name", request.tag.clone()))
    .bind(("tag_slug", tag_slug.clone()))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to ensure tag exists".to_string(),
        details: Some(e.to_string()),
    })?;

    // Create relation
    db.query(
        r#"
        LET $todo = (SELECT VALUE id FROM todos WHERE slug = $todo_slug LIMIT 1)[0];
        LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
        RELATE $todo->todo_tagged->$tag CONTENT { created_at: time::now() };
    "#,
    )
    .bind(("todo_slug", todo_slug.clone()))
    .bind(("tag_slug", tag_slug))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to add tag to TODO".to_string(),
        details: Some(e.to_string()),
    })?;

    // Sync denormalized cache
    sync_todo_tags_cache(db, &todo_slug)
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to sync tag cache".to_string(),
            details: Some(e.to_string()),
        })?;

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Tag '{}' added to TODO '{}'", request.tag, todo_slug)
    })))
}

/// Remove a tag from a TODO item
pub async fn remove_tag_from_todo(
    State(state): State<AppState>,
    Path((todo_slug, tag_slug)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    let db = &state.db;

    // Delete the relation
    db.query(
        r#"
        LET $todo = (SELECT VALUE id FROM todos WHERE slug = $todo_slug LIMIT 1)[0];
        LET $tag = (SELECT VALUE id FROM tags WHERE slug = $tag_slug LIMIT 1)[0];
        DELETE todo_tagged WHERE in = $todo AND out = $tag;
    "#,
    )
    .bind(("todo_slug", todo_slug.clone()))
    .bind(("tag_slug", tag_slug.clone()))
    .await
    .map_err(|e| ErrorResponse {
        error: "Failed to remove tag from TODO".to_string(),
        details: Some(e.to_string()),
    })?;

    // Sync denormalized cache
    sync_todo_tags_cache(db, &todo_slug)
        .await
        .map_err(|e| ErrorResponse {
            error: "Failed to sync tag cache".to_string(),
            details: Some(e.to_string()),
        })?;

    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Tag '{}' removed from TODO '{}'", tag_slug, todo_slug)
    })))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::response::IntoResponse;

    #[test]
    fn test_publish_request_with_frontmatter() {
        let content = r#"---
title: Test Article
tags: ["rust", "leptos"]
---

# Introduction

This is a test article."#;

        let request = PublishArticleRequest {
            title: None,
            slug: None,
            description: None,
            content: content.to_string(),
            tags: None,
            author: None,
            published: None,
            featured: None,
            embedding: None,
            content_format: None,
            html_content: None,
        };

        // Just test that we can create the request
        assert!(!request.content.is_empty());
    }

    #[test]
    fn test_error_response_status_code() {
        let error = ErrorResponse {
            error: "Something went wrong".to_string(),
            details: Some("More info".to_string()),
        };
        let response = error.into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }

    #[test]
    fn test_error_response_without_details() {
        let error = ErrorResponse {
            error: "Failure".to_string(),
            details: None,
        };
        let response = error.into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }
}
