use axum::{
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Response},
    Json,
};
use chrono::Utc;
use serde::Serialize;
use shared::{BlogPost, PublishArticleRequest};

use crate::{
    actors::content_cache::InvalidateCache,
    services::markdown_processor::{generate_slug, parse_markdown},
    AppState,
};

/// Response for successful article publication
#[derive(Debug, Serialize)]
pub struct PublishArticleResponse {
    pub success: bool,
    pub slug: String,
    pub id: Option<String>,
    pub message: String,
}

/// Error response for article publication failures
#[derive(Debug, Serialize)]
pub struct ErrorResponse {
    pub error: String,
    pub details: Option<String>,
}

impl IntoResponse for ErrorResponse {
    fn into_response(self) -> Response {
        (StatusCode::BAD_REQUEST, Json(self)).into_response()
    }
}

/// Publish a new blog article
///
/// This endpoint accepts markdown content with optional frontmatter,
/// processes it into HTML, generates an embedding, and stores it in SurrealDB.
pub async fn publish_article(
    State(state): State<AppState>,
    Json(request): Json<PublishArticleRequest>,
) -> Result<Json<PublishArticleResponse>, ErrorResponse> {
    // Parse markdown content
    let parsed = parse_markdown(&request.content).map_err(|e| ErrorResponse {
        error: "Failed to parse markdown".to_string(),
        details: Some(e),
    })?;

    // Determine title (from frontmatter or request)
    let title = request
        .title
        .or_else(|| parsed.frontmatter.as_ref().and_then(|fm| fm.title.clone()))
        .ok_or_else(|| ErrorResponse {
            error: "Title is required".to_string(),
            details: Some("Provide title in request or frontmatter".to_string()),
        })?;

    // Generate slug (from request, frontmatter, or title)
    let slug = request.slug.unwrap_or_else(|| generate_slug(&title));

    let tags = request
        .tags
        .or_else(|| parsed.frontmatter.as_ref().and_then(|fm| fm.tags.clone()))
        .unwrap_or_default();

    let author = request
        .author
        .or_else(|| parsed.frontmatter.as_ref().and_then(|fm| fm.author.clone()))
        .unwrap_or_else(|| "Admin".to_string());

    let published = request
        .published
        .or_else(|| parsed.frontmatter.as_ref().and_then(|fm| fm.published))
        .unwrap_or(true);

    let featured = request
        .featured
        .or_else(|| parsed.frontmatter.as_ref().and_then(|fm| fm.featured))
        .unwrap_or(false);

    // Generate vector embedding if provided in request
    // (CLI tool will generate embeddings locally and send them)
    let embedding = request.embedding;

    // Create BlogPost record
    let blog_post = BlogPost {
        id: None, // Will be generated by SurrealDB
        slug: slug.clone(),
        title: title.clone(),
        content: parsed.markdown_content.clone(),
        html_content: parsed.html_content,
        published_at: Utc::now(),
        updated_at: None,
        author,
        tags,
        featured,
        published,
        reading_time_minutes: parsed.reading_time_minutes,
        embedding,
    };

    // Insert into SurrealDB
    let db = &state.db;
    let created_post: Option<BlogPost> =
        db.create("blog_posts")
            .content(blog_post)
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to create blog post in database".to_string(),
                details: Some(e.to_string()),
            })?;

    let created_post = created_post.ok_or_else(|| ErrorResponse {
        error: "No blog post returned from database".to_string(),
        details: None,
    })?;

    // Invalidate content cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(PublishArticleResponse {
        success: true,
        slug: slug.clone(),
        id: created_post.id,
        message: format!("Article '{}' published successfully", title),
    }))
}

/// Delete a blog article by slug (admin only)
#[allow(dead_code)]
pub async fn delete_article(
    State(state): State<AppState>,
    slug: String,
) -> Result<Json<serde_json::Value>, ErrorResponse> {
    // Delete from SurrealDB
    let db = &state.db;

    // First find the article
    let query = "SELECT * FROM blog_posts WHERE slug = $slug LIMIT 1";
    let mut result = db
        .query(query)
        .bind(("slug", slug.clone()))
        .await
        .map_err(|e| ErrorResponse {
            error: "Database query failed".to_string(),
            details: Some(e.to_string()),
        })?;

    let posts: Vec<BlogPost> = result.take(0).map_err(|e| ErrorResponse {
        error: "Failed to parse query result".to_string(),
        details: Some(e.to_string()),
    })?;

    if posts.is_empty() {
        return Err(ErrorResponse {
            error: "Article not found".to_string(),
            details: Some(format!("No article with slug '{}'", slug)),
        });
    }

    // Delete the article
    let post_id = posts[0].id.as_ref().ok_or_else(|| ErrorResponse {
        error: "Article has no ID".to_string(),
        details: None,
    })?;

    let _: Option<BlogPost> =
        db.delete(("blog_posts", post_id))
            .await
            .map_err(|e| ErrorResponse {
                error: "Failed to delete article".to_string(),
                details: Some(e.to_string()),
            })?;

    // Invalidate cache
    let _ = state.content_cache.ask(InvalidateCache).await;

    Ok(Json(serde_json::json!({
        "success": true,
        "message": format!("Article '{}' deleted successfully", slug)
    })))
}

#[cfg(test)]
mod tests {
    use super::*;
    use axum::response::IntoResponse;

    #[test]
    fn test_publish_request_with_frontmatter() {
        let content = r#"---
title: Test Article
tags: ["rust", "leptos"]
---

# Introduction

This is a test article."#;

        let request = PublishArticleRequest {
            title: None,
            slug: None,
            description: None,
            content: content.to_string(),
            tags: None,
            author: None,
            published: None,
            featured: None,
            embedding: None,
        };

        // Just test that we can create the request
        assert!(!request.content.is_empty());
    }

    #[test]
    fn test_error_response_status_code() {
        let error = ErrorResponse {
            error: "Something went wrong".to_string(),
            details: Some("More info".to_string()),
        };
        let response = error.into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }

    #[test]
    fn test_error_response_without_details() {
        let error = ErrorResponse {
            error: "Failure".to_string(),
            details: None,
        };
        let response = error.into_response();
        assert_eq!(response.status(), StatusCode::BAD_REQUEST);
    }
}
