[package]
name = "plinth-shared"
version.workspace = true
edition.workspace = true

[dependencies]
plinth-person = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }

[features]
default = ["brick-blog", "brick-portfolio", "brick-todo", "brick-activity"]
brick-blog = []
brick-portfolio = []
brick-todo = []
brick-activity = []
config-toml = ["dep:toml", "dep:thiserror"]
