[package]
name = "plinth-shared"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
chrono = { workspace = true }
surrealdb = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }
toml = { workspace = true }

[features]
default = ["brick-blog", "brick-portfolio", "brick-todo"]
brick-blog = []
brick-portfolio = []
brick-todo = []
db = ["surrealdb"]
